# Generated by Django 6.0 on 2025-12-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='company',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(default='Неизвестная компания', max_length=255, verbose_name='Компания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='profession_category',
            field=models.CharField(choices=[('IT', 'IT и разработка'), ('FINANCE', 'Финансы'), ('SALES', 'Продажи'), ('MARKETING', 'Маркетинг'), ('MANAGEMENT', 'Управление'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название вакансии'),
        ),
    ]
